USE aidline;

ALTER TABLE users
  ADD COLUMN IF NOT EXISTS mother_full_name VARCHAR(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS family_name VARCHAR(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS sejel_number VARCHAR(50) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS date_of_birth DATE DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS generated_identity_id VARCHAR(128) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS initials_hash VARCHAR(32) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS intake_completed BOOLEAN DEFAULT FALSE;

ALTER TABLE onboarding_responses
  ADD COLUMN IF NOT EXISTS is_displaced BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS lost_house BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS occupation ENUM('student', 'freelancer', 'employee', 'unemployed', 'looking_for_a_job') DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS major VARCHAR(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS employee_lost_job_due_to_war BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS health_issues BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS health_issue_details TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS has_elderly_at_home BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS wants_to_volunteer BOOLEAN DEFAULT FALSE;
